#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update|delete|ssl <SSH_KEY> <RECORD_SET> <DOMAIN_NAME>"
  echo "e.g. $0 create|update|delete|ssl default app example.com"
  exit 1
else
  RECORD_SET=${3:=app}
  # Sets your external IP
  #IPADDRESS=`wget -qO- http://ipecho.net/plain ; echo -n`

  # Create a stack name based on the DomainName
  # Cloudformation doesn't accept periods in names
  if [ "$AWS_DEFAULT_PROFILE" != "$RECORD_SET-`echo $4 | sed -e 's/\./\-/g'`" ]; then
    export AWS_DEFAULT_PROFILE=$RECORD_SET-`echo $4 | sed -e 's/\./\-/g'`
    # Configures the aws-cli, requires an access key id and secret
    aws configure --profile $AWS_DEFAULT_PROFILE
  else 
    echo "Using default profile $AWS_DEFAULT_PROFILE"
  fi
  if [ "$1" == "ssl" ]; then
    aws iam upload-server-certificate \
      --server-certificate-name $3.$4 \
      --certificate-body file://$3.$4.crt \
      --private-key file://$3.$4.key 
  else
    if [ "$1" != "delete" ]; then
      # Creates a CloudFormation stack for the s3 bucket website
      aws cloudformation $1-stack \
        --stack-name $AWS_DEFAULT_PROFILE \
        --template-body file://cloudformation.json \
        --capabilities CAPABILITY_IAM \
        --parameters \
ParameterKey=KeyName,ParameterValue=$2 \
ParameterKey=DNSDomain,ParameterValue=$4
    else
      aws cloudformation delete-stack --stack-name $AWS_DEFAULT_PROFILE
    fi
  fi
fi
