#!/bin/bash
ENV_FILE=${ENV_FILE:-environment.variables}
if [ ! -e $ENV_FILE ]; then
  echo "No environment variables specified"
  exit 1
else
  source $ENV_FILE
  docker run -d -p 80:3000 --env-file $ENV_FILE $IMAGE_NAME:$VERSION
fi
